---
title: "Data - Flickr"
author: "Jan Overgoor"
params:
  date: "Sys.Date()"
output:
  html_document:
    code_folding: hide
    self_contained: yes
    toc: no
  pdf_document:
    toc: no
---

* Source: [http://socialnetworks.mpi-sws.org/data-wosn2008.html](http://socialnetworks.mpi-sws.org/data-wosn2008.html)
* Paper:  [https://people.mpi-sws.org/~amislove/publications/Growth-WOSN.pdf](https://people.mpi-sws.org/~amislove/publications/Growth-WOSN.pdf)



```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo=F, warning=F, cache=T, message=F, fig.width=6, fig.height=2.5)
suppressPackageStartupMessages(library('ggplot2'))
ggplot2::theme_set(theme_minimal())
library(tidyr)
library(dplyr)
library(readr)
library(mlogit)
library(stringr)
library(scales)
```

```{r}
# cleaner theme
my_theme <- function(base_size=10) {
  # Set the base size
  theme_bw(base_size=base_size) +
    theme(
      # Center title
      plot.title = element_text(hjust = 0.5),
      # Make the background white
      panel.background=element_rect(fill='white', colour='white'),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      # Minimize margins
      plot.margin=unit(c(0.2, 0.2, 0.2, 0.2), "cm"),
      panel.margin=unit(0.25, "lines"),
      # Tiny space between axis labels and tick labels
      axis.title.x=element_text(margin=ggplot2::margin(t=6.0)),
      axis.title.y=element_text(margin=ggplot2::margin(r=6.0)),
      # Simplify the legend
      legend.key=element_blank(),
      legend.title=element_blank(),
      legend.background=element_rect(fill='transparent')
    )
}

cdf <- Vectorize(function(x, a, xmin){
  # (a-1)/xmin * (x/xmin)^(-a)
  (x/xmin)^(-a+1)
  #my_zeta(a, x) / my_zeta(a, xmin)
})

my_zeta <- Vectorize(function(a, xmin) {
  sum((0:100000 + xmin)^(-a))
})

plot_powerlaw_cdf <- function(X, title, xlab, ylab) {
  X = X[X>0]
  fit = plfit(X, "range", seq(1.001,4,0.01))
  print(sprintf("plfit:  alpha=%.3f  xmin=%d", fit$alpha, fit$xmin))
  DF = data.frame(x=1:max(X)) %>%
    left_join(data.frame(x=X) %>% group_by(x) %>% summarize(n=n()), by='x') %>%
    mutate(n=ifelse(is.na(n), 0, n)) %>%
    mutate(p=(sum(n)-cumsum(n))/sum(n))
  ggplot(DF, aes(x, p)) + geom_point() +
    ggtitle(title) +
    scale_x_log10(xlab, breaks=c(1,10,100,1000,10000), labels=trans_format('log10', math_format(10^.x))) +
    scale_y_log10(ylab, breaks=c(10e-1, 10e-2, 10e-3, 10e-4, 10e-5, 10e-6, 10e-7), labels=trans_format('log10', math_format(10^.x))) +
    geom_line(data=data.frame(x=fit$xmin:max(X)) %>% mutate(p=cdf(x, fit$alpha, fit$xmin)*DF$p[fit$xmin]), color='red') +
    geom_text(aes(x=5, y=.01, label=sprintf('xmin=%d\nalpha=%.3f', fit$xmin,  fit$alpha))) +
    my_theme() #+ theme(text=element_text(family="Garamond", size=14))
}

acc <- function(f, data) {
  # compute predictions
  P = predict(f, newdata=data) %>% as.data.frame()
  inner_join(
    # actuals
    data %>% filter(y) %>% mutate(choice_id=as.character(choice_id)) %>% select(choice_id, correct=alt_id),
    # predicted
    P %>% mutate(choice_id=rownames(P)) %>% gather(choice, score, -choice_id) %>% group_by(choice_id) %>% filter(score==max(score)),
    by='choice_id'
  ) %>% ungroup() %>%
    summarize(acc=mean(choice==correct)) %>% .$acc %>% as.numeric()
}
```

```{r}
source("http://tuvalu.santafe.edu/~aaronc/powerlaws/plfit.r")
```

Read data

```{r}
d <- read_tsv("~/projects/choosing_to_grow/choose2grow/data/flickr-growth.txt.gz",
              #n_max=100,
              col_names=c('from','to','ds'), col_types='iiD')

nodes <- full_join(
    d %>% mutate(node=from) %>% group_by(node) %>% summarize(n_out=n(), first_out=min(ds)),
    d %>% mutate(node=to  ) %>% group_by(node) %>% summarize(n_in =n(), first_in =max(ds)),
    by='node'
  ) %>%
  mutate(n_out=ifelse(is.na(n_out), 0, n_out),
         n_in =ifelse(is.na(n_in ), 0, n_in ))
```

* total number of nodes: `r nrow(nodes)`
* total number of edges: `r nrow(d)`
* avg in-degree `r mean(nodes$n_in)`
* avg out-degree `r mean(nodes$n_out)`

Number of connections by day

```{r}
d %>% group_by(ds) %>% summarize(n=n()) %>% ggplot(aes(ds, n)) + geom_point() +
  scale_y_continuous("Number of new edges", limits=c(0, 3e+05)) +
  xlab("Date") + my_theme()
```

In/out degree

```{r plot_degdist}
Rmisc::multiplot(
  plot_powerlaw_cdf(nodes$n_out, title="cdf - Out links",
                    xlab="(log) Number of Links out", ylab="(log) Number of Accounts"),
  plot_powerlaw_cdf(nodes$n_in, title="cdf - In links",
                    xlab="(log) Number of Links in", ylab="(log) Number of Accounts"),
  cols=2
)
```


## Jackson R

```{r}
r_jackson <- function(deg_dist, m, tol=0.00000001 , r0=1.3, r1=1.7, max_iter=500){
  LHS <- 1 - log(1 - deg_dist + 0.0001)
  delta <- abs(r0 - r1)
  k <- 1
  while(delta > tol & k < 50){
    RHS <- log(seq(1, length(deg_dist), 1) + r0 * m)
    linearMod <- lm(LHS ~ 0 + RHS)
    r1 <- summary(linearMod)$coefficients[1,1]
    delta <- abs(r0 - r1)
    r0 <- r1
    k <- k + 1
  }
  r1
}


DFj <- nodes %>% mutate(degree=n_in) %>%
  group_by(degree) %>% summarize(n=n()) %>% ungroup() %>%
  arrange(degree) %>%
  complete(degree = seq(max(degree)), fill=list(n=0)) %>%
  mutate(D_d=cumsum(n), F_d=cumsum(n)/sum(n))

rstar = r_jackson(DFj$F_d, mean(nodes$n_out))
r = rstar/(1+rstar)
```

* Fitted $r^{*}=$ `r round(rstar, 3)`
* Fitted $r=\frac{r^{*}}{1+r^{*}}=$ `r round(r, 3)`


## Model

```{r read_data}
ds = c('061105','070301')[1]
fn <- sprintf("~/projects/choosing_to_grow/choose2grow/data/flickr-growth_choices_%s.csv", ds)
DM <- read_csv(fn, col_types='iiiii') %>%
  mutate(
    is_fof=as.factor(ifelse(is.na(hops), 0, ifelse(hops > 2, 0, 1))),
    hops_f=as.factor(ifelse(is.na(hops), 'none', ifelse(hops >=6 , '6+', as.character(hops)))),
    hops_f=factor(hops_f, levels=c("none","2","3","4","5","6+"))
  )
```

```{r sample_data}
set.seed(100)
H_train <- DM %>% inner_join(DM %>% distinct(choice_id) %>% sample_n(5000), by='choice_id') %>%
     group_by(choice_id) %>% mutate(alt_id=row_number()) %>% ungroup() %>%
     select(choice_id, alt_id, y, deg:hops_f) %>%
     mlogit.data(shape="long", chid.var='choice_id', choice="y", alt.var='alt_id')

set.seed(101)
H_test <- DM %>% inner_join(DM %>% distinct(choice_id) %>% sample_n(1000), by='choice_id') %>%
     group_by(choice_id) %>% mutate(alt_id=row_number()) %>% ungroup() %>%
     select(choice_id, alt_id, y, deg:hops_f) %>%
     mlogit.data(shape="long", chid.var='choice_id', choice="y", alt.var='alt_id')
```

```{r model_models}
#f1 <- mlogit(y ~ log(deg+1) | 0, H_train)
f1 <- mlogit(y ~ log(deg+1) + reciprocal| 0, H_train)
f2 <- mlogit(y ~ log(deg+1) + reciprocal + is_fof | 0, H_train)
f3 <- mlogit(y ~ log(deg+1) + reciprocal + hops_f | 0, H_train)
#f3b <- mlogit(y ~ log(deg+1) + is_fof + hops_f | 0, H_train)  # singular
#f4 <- mlogit(y ~ log(deg+1) + reciprocal | 0, H_train)
#f4 <- mlogit(y ~ log(deg+1) + is_fof + reciprocal | 0, H_train)
```

```{r sg_text}
stargazer::stargazer(
  f1, f2, f3,
  dep.var.caption = "",
  covariate.labels = c("log In-Degree", "Reciprocal", "Is FoF",
                       "2 Hops", "3 Hops", "4 Hops", "5 Hops", "6+ Hops"),
  header=FALSE, 
  type='text')
```

```{r accuracy}
print("Train accuracy:")
print(c(acc(f1, H_train), acc(f2, H_train), acc(f3, H_train)))
print("Test accuracy:")
print(c(acc(f1, H_test), acc(f2, H_test), acc(f3, H_test)))

```
